#ifndef AST_ASSIGNMENT_OPERATOR_H
#define AST_ASSIGNMENT_OPERATOR_H

typedef enum {
    AST_ASSIGNMENT_OPERATOR_TOK_SRA_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_PLUS_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_MOD_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_SR_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_AND_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_DIV_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_MUL_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_OR_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_SLA_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_SL_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_XOR_EQ,
    AST_ASSIGNMENT_OPERATOR_TOK_MINUS_EQ
} ast_assignment_operator_t;

void ast_assignment_operator_print(ast_assignment_operator_t assignment_operator);

#endif
