#ifndef AST_OVERLOAD_OPERATOR_H
#define AST_OVERLOAD_OPERATOR_H

typedef enum {
    AST_OVERLOAD_OPERATOR_TOK_PLUS,
    AST_OVERLOAD_OPERATOR_TOK_INC,
    AST_OVERLOAD_OPERATOR_TOK_PWR,
    AST_OVERLOAD_OPERATOR_TOK_EQ,
    AST_OVERLOAD_OPERATOR_TOK_LOG_GT,
    AST_OVERLOAD_OPERATOR_TOK_MINUS,
    AST_OVERLOAD_OPERATOR_TOK_LOG_LT,
    AST_OVERLOAD_OPERATOR_TOK_MUL,
    AST_OVERLOAD_OPERATOR_TOK_LOG_LEQ,
    AST_OVERLOAD_OPERATOR_TOK_MOD,
    AST_OVERLOAD_OPERATOR_TOK_LOG_GEQ,
    AST_OVERLOAD_OPERATOR_TOK_LOG_NEQ,
    AST_OVERLOAD_OPERATOR_TOK_DIV,
    AST_OVERLOAD_OPERATOR_TOK_LOG_EQ,
    AST_OVERLOAD_OPERATOR_TOK_DEC
} ast_overload_operator_t;

void ast_overload_operator_print(ast_overload_operator_t overload_operator);

#endif
